# Generated by Django 3.2 on 2021-04-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
    ]
